const products = [
    {
        "product_id":"1",
        "product_name": "Laundry Busket with Lid - A Laxurious Design Combining Elegance, Privacy, and Perfect Organization concept_home",
        "barcode": "6287018853949",
        "partnerSku": "063-08-3380-02",
        "sku": "Z571F1249538DDBBC99A7Z-1",
        "packing": "80 number Plastic",
        "color": "White",
        "noon_barcode": "6308338002",
        "amazon_barcode": "",
        "image":"../images/laundry-basket-luxurious.jpg",
        "description": "null"
    },
    {
        "product_id":"2",
        "product_name": "3-Tier Shoe Rack Organizer Beige 55.5x21.7x61 cm 9 Paris of Shoe concept_home",
        "barcode": "",
        "partnerSku": "046-08-3555B-03",
        "sku": "ZFCC4A1B3F20A426977D3Z-1",
        "packing": "null",
        "color": "Beige",
        "noon_barcode": "65170842031",
        "amazon_barcode": "",
        "image":"../images/3-tier-shoe-rack.jpg",
        "description": "null"
    },
    {
        "product_id":"3",
        "product_name": "Plastic Storage Box Multipurpose Transparent Plastic Storage Box With Wheels And Lockable Lid 80L Clear/black concept_home",
        "barcode": "",
        "partnerSku": "058-08-1180-18",
        "sku": "Z4002AA5C55019F8DD884Z-1",
        "packing": "null",
        "color": "Transparent",
        "noon_barcode": "690332808080",
        "amazon_barcode": "",
        "image":"../images/storage-box-80-liters.jpg",
        "description": "Fredy"
    },
    {
        "product_id":"4",
        "product_name": "3-Tier Multipurpose Rolling Shelves Cart Organizer White 83x53.5x32cm concept_home",
        "barcode": "",
        "partnerSku": "044-08-4359B-02",
        "sku": "ZD5EB47809C9CCDB35548Z-1",
        "packing": "Roll",
        "color": "White",
        "noon_barcode": "6287015356979",
        "amazon_barcode": "",
        "image":"../images/Rolling Shelf Organizer 3-Tier White.jpg",
        "description": "359B"
    },
    {
        "product_id":"5",
        "product_name": "3-Tier Multipurpose Rolling Shelves Cart Organizer Black 83x53.5x32cm concept_home",
        "barcode": "",
        "partnerSku": "044-08-4359B-01",
        "sku": "Z0D3FD1EB8D17AB5B29CDZ-1",
        "packing": "Roll",
        "color": "Black",
        "noon_barcode": "6287015359031",
        "amazon_barcode": "X002FINPKZ",
        "image":"../images/Rolling Shelf Organizer 3-Tier Black.jpg",
        "description": "359B"
    },
    {
        "product_id":"6",
        "product_name": "4 pieces Trash bin for offices and rooms, Beige 13.5 liter concept_home",
        "barcode": "",
        "partnerSku": "043-08-3264-03*4",
        "sku": "ZA0C41617055314D4DBA3Z-1",
        "packing": "18 number Plastic",
        "color": "Beige",
        "noon_barcode": "43083264034",
        "amazon_barcode": "",
        "image":"../images/ikea Trash bin Beige.jpg",
        "description": ""
    },
    {
        "product_id":"7",
        "product_name": "Laundry Basket With Lid - A Luxurious Design Combining Elegance, Privacy, and Perfect Organization concept-home",
        "barcode": "6287000282641",
        "partnerSku": "063-08-2248-02",
        "sku": "Z318C1A68BC07A606E9E2Z-1",
        "packing": "28 Number Plastic",
        "color": "White",
        "noon_barcode": "2763487952487",
        "amazon_barcode": "",
        "image":"../images/Laundry basket with Lid Luxurious design White 60 Liters.jpg",
        "description": "aap Art No.: 1-00248, 60 Liters"
    },
    {
        "product_id":"8",
        "product_name": "Plastic Storage Box Multipurpose Transparent Plastic Storage box With Lockable Lid 30L Clear/Black concept_home",
        "barcode": "6287018852126",
        "partnerSku": "058-08-1430-18",
        "sku": "Z64B70B63E1B45849B0C2Z-1",
        "packing": "24 Number Plastic",
        "color": "Tranparent Clear/Black",
        "noon_barcode": "690058081130",
        "amazon_barcode": "",
        "image":"../images/Storage box transparent 30 Liters.jpg",
        "description": "30 Liters"
    },
    {
        "product_id":"9",
        "product_name": "12-pces Cawa Cups White/Green/Red 60Ml | 90 ML / 120 ML badraig",
        "barcode": "6901200381224",
        "partnerSku": "008-09-1603-13",
        "sku": "ZC539FDFD25305110E045Z-3",
        "packing": "Bubble",
        "color": "Red",
        "noon_barcode": "6901200381224",
        "amazon_barcode": "",
        "image":"../images/cawa cups Red 120.jpg",
        "description": "YW-RED-120 ML, 120cc CAWA CUP"
    },
    {
        "product_id":"10",
        "product_name": "12-pces Cawa Cups White/Green/Red 60Ml | 90 ML / 120 ML badraig",
        "barcode": "6901200621054",
        "partnerSku": "008-09-1602-13",
        "sku": "ZC539FDFD25305110E045Z-2",
        "packing": "Bubble",
        "color": "Red",
        "noon_barcode": "6901200621054",
        "amazon_barcode": "",
        "image":"../images/Cawa cups Red 90.jpg",
        "description": "YW-RED-90 ML, 90cc CAWA CUP"
    },
    {
        "product_id":"11",
        "product_name": "Plastic Storage Box Multipurpose Transparent Plastic Storage Box With Wheels And Lockable Lid 120L Clear/Black concept_home",
        "barcode": "6207000283181",
        "partnerSku": "058-08-41120-18",
        "sku": "Z491119646C92B8BD5FEEZ-1",
        "packing": "Plastic not sure",
        "color": "Clear",
        "noon_barcode": "66911150150",
        "amazon_barcode": "",
        "image":"../images/Storage box transparent 120 liters.jpg",
        "description": "Alabras Plastic, 120 Ltr - 75x52.5 45.5 Cm, 1-00289"
    },
    {
        "product_id":"12",
        "product_name": "Meshed Elegant and Modern Design Round Trash Can White 8 L concept_home",
        "barcode": "6956852330649",
        "partnerSku": "043-01-1108-02",
        "sku": "Z11837ECA7EA5C405C085Z-1",
        "packing": "Plastic not sure",
        "color": "White",
        "noon_barcode": "6956852330649",
        "amazon_barcode": "",
        "image":"../images/Metal wastepaper basket 8 Liters White.jpg",
        "description": "Box item No: B0050s NB, PCS/CTN: 12PCS, LOT NUMBER: 26HT41508"
    },
    {
        "product_id":"13",
        "product_name": "Meshed Elegant and Modern Design Round Trash Can Black 8 L concept_home",
        "barcode": "6956852330632",
        "partnerSku": "043-01-1108-01",
        "sku": "ZE37C7DE70CD6193D2CE1Z-1",
        "packing": "Plastic not sure",
        "color": "Black",
        "noon_barcode": "6956852330632",
        "amazon_barcode": "",
        "image":"../images/Metal wastepaper basket 8 Liters Black.jpg",
       "description": "item no: B0050S NB, LOT Number: 26HT41508"
    },
    {
        "product_id":"14",
        "product_name": "3-Layer Storage Shelve Organizer For Bathroom, Kitchen With Wheels White concept_home",
        "barcode": "6287000283297",
        "partnerSku": "044-08-5300-02",
        "sku": "Z8C387D3EDB39EB10F679Z-1",
        "packing": "none",
        "color": "White",
        "noon_barcode": "6517084003",
        "amazon_barcode": "",
        "image":"../images/3-layer bathroom kitchen trolly white.jpg",
        "description": "Al Abras Plastic, 1-00300"
    },
    {
        "product_id":"15",
        "product_name": "4-Piece Aluminium Cookware Pot Set Silver elamal",
        "barcode": "9633000010581",
        "partnerSku": "004-02-1204",
        "sku": "Z7F7D4A4216DFC5958C85Z-1",
        "packing": "none",
        "color": "",
        "noon_barcode": "9633000010581",
        "amazon_barcode": "",
        "image":"../images/Elamal cookware khaleji.jpg",
        "description": "Pure Alumium Set 4, Cookware since 1969"
    },
    {
        "product_id":"16",
        "product_name": "Machine Basket Rice Wash Sieve Strainer White 22.8x26.5x19.5 cm concept_home",
        "barcode": "",
        "partnerSku": "052-08-3226-02",
        "sku": "Z64A3CF07335A679402D3Z-1",
        "packing": "14 number Plastic",
        "color": "White",
        "noon_barcode": "65112254559",
        "amazon_barcode": "",
        "image":"../images/Strainer white Rice wash.jpg",
        "description": "2 in 1 COLANDER Drain and serve, art no. 226"
    },
    {
        "product_id":"17",
        "product_name": "",
        "barcode": "6287000283174",
        "partnerSku": "",
        "sku": "",
        "packing": "",
        "color": "Transparent",
        "noon_barcode": "",
        "amazon_barcode": "",
        "image":"../images/Storage Box 80 Liters Transparent Al-Abras Plastic.jpg",
        "description": "80. Ltr - 62 x 44 x 42 Cm, 1-00288 Al-Abras Plastic"
    },
    {
        "product_id":"18",
        "product_name": "",
        "barcode": "6287015357327",
        "partnerSku": "",
        "sku": "",
        "packing": "Roll",
        "color": "White / Beige",
        "noon_barcode": "",
        "amazon_barcode": "",
        "image":"../images/Wooden Drawer Big - 6 Layer No-856.jpg",
        "description": "Wooden Drawer Big (6 Layer) Art No.856, item Code: I-SH-856-WHT"
    },
    {
        "product_id":"19",
        "product_name": "",
        "barcode": "6287015357310",
        "partnerSku": "",
        "sku": "",
        "packing": "Roll",
        "color": "White / Beige",
        "noon_barcode": "",
        "amazon_barcode": "",
        "image":"../images/Wooden Drawer Big - 5 Layer No-855.jpg",
        "description": "Wooden Drawer Big (5 Layer) Art No.855, item Code: I-SH-855-WHT"
    },
    {
        "product_id":"20",
        "product_name": "",
        "barcode": "6287015357303",
        "partnerSku": "",
        "sku": "",
        "packing": "Roll",
        "color": "White / Beige",
        "noon_barcode": "",
        "amazon_barcode": "",
        "image":"../images/Wooden Drawer Big - 4 Layer No-854.jpg",
        "description": "Wooden Drawer Big (4 Layer) Art No.854, item Code: I-SH-854-WHT"
    },
    {
        "product_id":"21",
        "product_name": "",
        "barcode": "6287015350304",
        "partnerSku": "",
        "sku": "",
        "packing": "",
        "color": "Gray",
        "noon_barcode": "",
        "amazon_barcode": "",
        "image":"../images/30 Liters Garbage bin Trash can Plasticna.jpg",
        "description": "Trash Bin 503 Grey 26, 30 Liters, Plasticna"
    },
    {
        "product_id":"22",
        "product_name": "",
        "barcode": "6287015350311",
        "partnerSku": "",
        "sku": "",
        "packing": "",
        "color": "Gray",
        "noon_barcode": "",
        "amazon_barcode": "",
        "image":"../images/50 Liters Garbage bin Trash can Plasticna.jpg",
        "description": "Trash Bin 504 Grey 26, 50 Liters, Plasticna"
    },
    {
        "product_id":"23",
        "product_name": "2 Pack Laundry Basket 40 Liter Freestanding Laundry Hamper for Clothes, Blankets, Cushions concept_home",
        "barcode": "6287015351943",
        "partnerSku": "063-08-1485-02*2",
        "sku": "ZF570E73826E56FAAD029Z-1",
        "packing": "30 Number Plastic",
        "color": "White",
        "noon_barcode": "69000148502P2",
        "amazon_barcode": "",
        "image":"../images/Laundry Basket 40 Liters White Plasticna.jpg",
        "description": "Laundry Basket 485 White 66, 40 Liter"
    },
    {
        "product_id":"24",
        "product_name": "Foldable Plastic Storage Box 4 layers With Wheels and Doors Storage Bin with Lid Organizers Stackable Storage Bins, Closet Organizers Double Door Magnetic with Universal Pulley concept_home",
        "barcode": "",
        "partnerSku": "045-08-4104-02(1",
        "sku": "ZF7B93BC0CEA712A8CE34Z-1",
        "packing": "none",
        "color": "Clear Brown door, custard cream shell",
        "noon_barcode": "6912400085139",
        "amazon_barcode": "",
        "image":"../images/4 Layer 8040-4 Plastic foldable shoe box.jpg",
        "description": "8040-4, G.W 2.9 Kgs, N.W 2.4 Kgs, Cartoon size: 40.3*20.5*29.3 cm"
    },
    {
        "product_id":"25",
        "product_name": "5- Layers Plastic Storage Bins with Lids, Stackable Storage Containers with Wheels, Folding Storage Boxes, Collapsible Storage Bins, Multi-Purpose Folding Storage Containers for Home and Office concept_home",
        "barcode": "",
        "partnerSku": "045-08-4105-02",
        "sku": "Z17C2EB293005138290E8Z-1",
        "packing": "none",
        "color": "Clear Brown door, custard cream shell",
        "noon_barcode": "69000804055",
        "amazon_barcode": "",
        "image":"../images/5 Layer 8040-5 Plastic foldable shoe box.jpg",
        "description": "8040-5, G.W 3.6 Kgs, N.W 3 Kgs, Cartoon size: 40.3*26.3*29.3 cm"
    },
    {
        "product_id":"26",
        "product_name": "",
        "barcode": "6287015353749",
        "partnerSku": "",
        "sku": "",
        "packing": "none",
        "color": "White / Beige",
        "noon_barcode": "65450381899",
        "amazon_barcode": "",
        "image":"../images/Classic Drawer (5 Layer) Art No 635.jpg",
        "description": "Classic 5 Layer, item Code: I-SH-635-MIX-WHT"
    },
    {
        "product_id":"27",
        "product_name": "5-Layer Storage Drawer Cabinet Wooden Design White/Beige 42x104x34 cm concept_home",
        "barcode": "6287015356900",
        "partnerSku": "045-08-3655-02",
        "sku": "ZC18389D137B52457E781Z-1",
        "packing": "none",
        "color": "White / Beige",
        "noon_barcode": "4508365502",
        "amazon_barcode": "",
        "image":"../images/Wooden Drawer (5 Layer) Art No 655.jpg",
        "description": "655, item code: I-SH-655-MIX-WHT"
    },
    {
        "product_id":"28",
        "product_name": "Plastic Storage Box Multipurpose Transparent Plastic Storage Box With Wheels And Lockable Lid 45L Clear/Black concept_home",
        "barcode": "6287018852812",
        "partnerSku": "058-08-1145-18",
        "sku": "Z368E66DFBD564C3CE652Z-1",
        "packing": "28 number Plastic",
        "color": "Clear/Black",
        "noon_barcode": "690332454545",
        "amazon_barcode": "",
        "image":"../images/Storage box 45 Liter Plastic Transparent.jpg",
        "description": "Transparent box 45 Liters"
    },
    {
        "product_id":"29",
        "product_name": "Plastic Storage Box Multipurpose Transparent Plastic Storage Box With Wheels And Lockable Lid 60L Clear/Black concept_home",
        "barcode": "6287018852829",
        "partnerSku": "058-08-1160-18",
        "sku": "Z8ABC5E7B5E3858ED0F22Z-1",
        "packing": "28 number Plastic",
        "color": "Clear/Black",
        "noon_barcode": "690332606060",
        "amazon_barcode": "",
        "image":"../images/Storage box 60 Liter Plastic Transparent.jpg",
        "description": "Plastic Storage Box 60 Liter Transparent"
    },
    {
        "product_id":"30",
        "product_name": "Plasticna Waste Bin I-BK-264-WHT Plastic White 13 Liters",
        "barcode": "6287015357747",
        "partnerSku": "043-08-3264-02",
        "sku": "Z58D96F08BBC134297902Z-1",
        "packing": "18 number Plastic",
        "color": "White",
        "noon_barcode": "6900026426402",
        "amazon_barcode": "",
        "image":"../images/Trash bin 13.5 Liter White White.jpg",
        "description": "Trash bin 264 White 46, Use concept_home"
    },
    {
        "product_id":"31",
        "product_name": "4-Layer Storage Shelve Organizer With Wheels White generic",
        "barcode": "6287000283303",
        "partnerSku": "044-08-5304-02",
        "sku": "ZD11CB304243B90DEC808Z-1",
        "packing": "none",
        "color": "White",
        "noon_barcode": "6517084004",
        "amazon_barcode": "",
        "image":"../images/4-Layer Storage Shelve Al-Abras Plastic White.jpg",
        "description": "4 Layer Trolly, Al-Abras Plastic, Art No.: 1-00300-4, Use concept_home"
    },
    {
        "product_id":"32",
        "product_name": "Modern Garbage for Office or Rooms White concept_home",
        "barcode": "6287015351073",
        "partnerSku": "043-08-3253-02",
        "sku": "ZC8DAADB17FCD70C93F87Z-1",
        "packing": "16 number Plastic",
        "color": "",
        "noon_barcode": "65434445521",
        "amazon_barcode": "",
        "image":"../images/Modern Garbage 7 Liter for office White.jpg",
        "description": "Large Paper Bin 253 White 56"
    },
    {
        "product_id":"33",
        "product_name": "Granite Pressure Cooker | Pressure Pot Arabic Cooker | Dark Grey/Beige Available Sizes 2L 3L 4L 5L 6L 7L 8L 9L 10L 11L 12L 15L badraig",
        "barcode": "6920913618403",
        "partnerSku": "001-03-103-05(1",
        "sku": "Z25C1E41D93A5B1BBA062Z-2",
        "packing": "none",
        "color": "Dark Grey",
        "noon_barcode": "6920913618403",
        "amazon_barcode": "",
        "image":"../images/3 Liter Dark Grey Pressure Cooker.jpg",
        "description": "3 Liter Dark Grey, item no: CTC18-3L"
    },
    {
        "product_id":"34",
        "product_name": "Aluminum Pressure Cooker Pressure Pot Arabic Cooker Silver Black Available Sizes 2L 3L 4L 5L 7L 9L 10L 11L 12L 15L badraig",
        "barcode": "6920913616003",
        "partnerSku": "001-02-102(1",
        "sku": "Z1FE8A8EF6171012FD66BZ-1",
        "packing": "Roll",
        "color": "Silver Black",
        "noon_barcode": "6920913616027",
        "amazon_barcode": "",
        "image":"../images/2 Liter Aluminium Pressure Cooker.jpg",
        "description": "Aluminium 2 Liter Pressure Cooker"
    },
    {
        "product_id":"35",
        "product_name": "Trash Basket for Office or Rooms Black concept_home",
        "barcode": "6287015355446",
        "partnerSku": "043-08-3253-01",
        "sku": "ZEB321D96B84A03EE69FCZ-1",
        "packing": "16 number Plastic",
        "color": "Black",
        "noon_barcode": "65434445522",
        "amazon_barcode": "",
        "image":"../images/Modern Garbage 7 Liter for office Black.jpg",
        "description": "Large Paper 7 Liter Bin 56, Art no. 253 Black"
    },
    // {
    //     "product_id":"36",
    //     "product_name": "",
    //     "barcode": "",
    //     "partnerSku": "",
    //     "sku": "",
    //     "packing": "",
    //     "color": "",
    //     "noon_barcode": "",
    //     "amazon_barcode": "",
    //     "image":"../images/.jpg",
    //     "description": ""
    // },
    // {
    //     "product_id":"37",
    //     "product_name": "",
    //     "barcode": "",
    //     "partnerSku": "",
    //     "sku": "",
    //     "packing": "",
    //     "color": "",
    //     "noon_barcode": "",
    //     "amazon_barcode": "",
    //     "image":"../images/.jpg",
    //     "description": ""
    // },
    // {
    //     "product_id":"38",
    //     "product_name": "",
    //     "barcode": "",
    //     "partnerSku": "",
    //     "sku": "",
    //     "packing": "",
    //     "color": "",
    //     "noon_barcode": "",
    //     "amazon_barcode": "",
    //     "image":"../images/.jpg",
    //     "description": ""
    // },
    // {
    //     "product_id":"39",
    //     "product_name": "",
    //     "barcode": "",
    //     "partnerSku": "",
    //     "sku": "",
    //     "packing": "",
    //     "color": "",
    //     "noon_barcode": "",
    //     "amazon_barcode": "",
    //     "image":"../images/.jpg",
    //     "description": ""
    // },
    // {
    //     "product_id":"40",
    //     "product_name": "",
    //     "barcode": "",
    //     "partnerSku": "",
    //     "sku": "",
    //     "packing": "",
    //     "color": "",
    //     "noon_barcode": "",
    //     "amazon_barcode": "",
    //     "image":"../images/.jpg",
    //     "description": ""
    // },
];

export default products;